# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmQzjvG5w-QGZit6_0Xb9W1e9pCOb5hb
"""

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# Daftar label kelas daun
class_names = [
    'Daun Jambu Biji', 'Daun Kari', 'Daun Kemangi', 'Daun Kunyit',
    'Daun Mint', 'Daun Pepaya', 'Daun Sirih', 'Daun Sirsak',
    'Lidah Buaya', 'Teh Hijau'
]

# Khasiat dari masing-masing daun
khasiat_daun = {
    'Daun Jambu Biji': 'Mengatasi diare, mempercepat penyembuhan luka.',
    'Daun Kari': 'Menurunkan kolesterol, antioksidan alami.',
    'Daun Kemangi': 'Menambah nafsu makan, antibakteri.',
    'Daun Kunyit': 'Anti inflamasi, memperlancar haid.',
    'Daun Mint': 'Meredakan sakit kepala dan mual.',
    'Daun Pepaya': 'Melancarkan pencernaan, anti kanker.',
    'Daun Sirih': 'Antiseptik, menghentikan pendarahan ringan.',
    'Daun Sirsak': 'Anti tumor, menurunkan tekanan darah.',
    'Lidah Buaya': 'Menyembuhkan luka bakar, melembapkan kulit.',
    'Teh Hijau': 'Menurunkan berat badan, antioksidan tinggi.'
}

# Load model
model = tf.keras.models.load_model('model_daun_herbal.h5')  # Sesuaikan dengan nama model kamu

# Preprocessing function
def preprocess_image(image):
    image = image.resize((224, 224))
    image = np.array(image) / 255.0
    return np.expand_dims(image, axis=0)

# UI Layout
st.set_page_config(page_title="Klasifikasi Daun Herbal", layout="centered")

st.markdown(
    "<h3 style='text-align: center;'>"
    "<span style='color:#0abf53;'>CARI</span> TANAMAN HERBAL<br>"
    "<span style='color:#1abc9c;'>DENGAN</span> SATU KLIK!!"
    "</h3>", unsafe_allow_html=True)

st.markdown("---")

uploaded_file = st.file_uploader("Unggah gambar daun", type=["jpg", "jpeg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar Daun", use_column_width=True)

    # Prediksi
    with st.spinner("Menganalisis gambar..."):
        input_image = preprocess_image(image)
        prediction = model.predict(input_image)
        predicted_class = class_names[np.argmax(prediction)]
        manfaat = khasiat_daun.get(predicted_class, "Khasiat tidak ditemukan.")

    # Tampilkan hasil
    st.markdown(
        f"<p style='text-align:center; font-size:20px;'>"
        f"<strong>Nama daun :</strong> {predicted_class}</p>",
        unsafe_allow_html=True
    )
    st.markdown(
        f"<p style='text-align:center; font-size:16px; color:#444;'>"
        f"Khasiat: {manfaat}</p>",
        unsafe_allow_html=True
    )

# Footer Icons
col1, col2, col3 = st.columns([1, 2, 1])
with col1:
    st.markdown('<div style="text-align:center;"><img src="https://img.icons8.com/ios/50/00e676/camera--v1.png" width="40"/></div>', unsafe_allow_html=True)
with col3:
    st.markdown('<div style="text-align:center;"><img src="https://img.icons8.com/ios/50/00e676/image.png" width="40"/></div>', unsafe_allow_html=True)